# Generated by Django 3.1.7 on 2021-03-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0004_auto_20210305_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='games')),
                ('cracker', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genre.genre')),
            ],
        ),
    ]
