# Generated by Django 3.1.7 on 2021-03-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20210305_1016'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
