# Generated by Django 3.1.7 on 2021-03-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20210305_1016'),
        ('games', '0003_game_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre'),
        ),
    ]
