# Generated by Django 3.1.7 on 2021-03-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210306_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='slug',
            new_name='game_slug',
        ),
    ]
