# Generated by Django 3.1.7 on 2021-03-07 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20210306_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='games'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
