# Generated by Django 3.1.7 on 2021-03-07 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210307_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='download',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
