# Generated by Django 3.1.7 on 2021-03-08 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='games/default.jpg', upload_to='games', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
