# Generated by Django 3.1.7 on 2021-03-08 13:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210308_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(default=' '),
        ),
    ]
