# Generated by Django 3.1.7 on 2021-03-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210308_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image2',
        ),
    ]
