# Generated by Django 3.1.7 on 2021-03-08 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_game_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(default='games/default.jpg', upload_to='games', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
