# Generated by Django 3.1.7 on 2021-03-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image2',
        ),
    ]
