# Generated by Django 3.1.7 on 2021-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_remove_game_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
