# Generated by Django 3.1.7 on 2021-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_game_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lang',
            field=models.CharField(default='English', max_length=30),
            preserve_default=False,
        ),
    ]
