# Generated by Django 3.1.7 on 2021-03-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_game_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cracker',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='lang',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
