# Generated by Django 3.1.5 on 2021-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
