# Generated by Django 3.1.5 on 2021-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20210303_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='default_genre.jpg', upload_to='genre'),
        ),
    ]
