# Generated by Django 3.1.7 on 2021-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_auto_20210303_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='genre\\default_genre.jpg', upload_to='genre'),
        ),
    ]
