# Generated by Django 3.1.7 on 2021-03-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20210305_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='slug',
            new_name='genre_slug',
        ),
    ]
