# Generated by Django 3.1.7 on 2021-03-07 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0007_auto_20210306_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='video',
            field=models.FileField(default='genre\\default_genre.jpg', upload_to='genre', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='genre\\default_genre.jpg', upload_to='genre', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
