# Generated by Django 3.1.7 on 2021-03-07 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0009_remove_genre_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='video',
            field=models.FileField(default='genre\x0bideos\\default.mp4', upload_to='genre\x0bideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wav'])]),
        ),
    ]
