# Generated by Django 3.1.7 on 2021-03-07 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0012_auto_20210307_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='video',
            field=models.FileField(default='gvideos\\default.mp4', upload_to='gvideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wav'])]),
        ),
    ]
