# Generated by Django 3.1.7 on 2021-03-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0013_auto_20210307_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='quote',
            field=models.CharField(default='', max_length=130),
        ),
    ]
